/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mortalkombat.Forms;

/**
 *
 * @author MyHuawei
 */
public class CannotUseItemDialog extends javax.swing.JDialog {

    /**
     * Creates new form CannotUseItemDialog
     */
    public CannotUseItemDialog() {
        //super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cannotUseItemPanel = new javax.swing.JPanel();
        cannotUseItemLabel = new javax.swing.JLabel();
        cannotUseItemLabel2 = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cannotUseItemPanel.setBackground(new java.awt.Color(243, 120, 120));

        cannotUseItemLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cannotUseItemLabel.setForeground(new java.awt.Color(51, 51, 51));
        cannotUseItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cannotUseItemLabel.setText("Вы не можете использовать ");

        cannotUseItemLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cannotUseItemLabel2.setForeground(new java.awt.Color(51, 51, 51));
        cannotUseItemLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cannotUseItemLabel2.setText("этот предмет");

        OkButton.setBackground(new java.awt.Color(204, 204, 204));
        OkButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        OkButton.setForeground(new java.awt.Color(51, 51, 51));
        OkButton.setText("ОК");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cannotUseItemPanelLayout = new javax.swing.GroupLayout(cannotUseItemPanel);
        cannotUseItemPanel.setLayout(cannotUseItemPanelLayout);
        cannotUseItemPanelLayout.setHorizontalGroup(
            cannotUseItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannotUseItemPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(cannotUseItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannotUseItemPanelLayout.createSequentialGroup()
                        .addComponent(cannotUseItemLabel)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannotUseItemPanelLayout.createSequentialGroup()
                        .addComponent(cannotUseItemLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(cannotUseItemPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cannotUseItemPanelLayout.setVerticalGroup(
            cannotUseItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannotUseItemPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(cannotUseItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cannotUseItemLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cannotUseItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cannotUseItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        dispose();
    }//GEN-LAST:event_OkButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel cannotUseItemLabel;
    private javax.swing.JLabel cannotUseItemLabel2;
    private javax.swing.JPanel cannotUseItemPanel;
    // End of variables declaration//GEN-END:variables
}
