/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mortalkombat.Forms;

/**
 *
 * @author MyHuawei
 */
public class EndGameDialog extends javax.swing.JDialog {

    /**
     * Creates new form EndGameDialog
     */
    public EndGameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winnerPanel = new javax.swing.JPanel();
        winnerLabel = new javax.swing.JLabel();
        notTop10Label = new javax.swing.JLabel();
        finishGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winnerPanel.setBackground(new java.awt.Color(255, 204, 255));

        winnerLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winnerLabel.setForeground(new java.awt.Color(255, 0, 0));
        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setText("Вы прошли все локации!");

        notTop10Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        notTop10Label.setForeground(new java.awt.Color(102, 102, 102));
        notTop10Label.setText("К сожалению, Ваш результат не попал в топ 10");

        finishGameButton.setBackground(new java.awt.Color(153, 153, 255));
        finishGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishGameButton.setForeground(new java.awt.Color(51, 51, 51));
        finishGameButton.setText("Закончить игру");
        finishGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winnerPanelLayout = new javax.swing.GroupLayout(winnerPanel);
        winnerPanel.setLayout(winnerPanelLayout);
        winnerPanelLayout.setHorizontalGroup(
            winnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winnerPanelLayout.createSequentialGroup()
                .addGroup(winnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winnerPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winnerPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(notTop10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winnerPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(finishGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        winnerPanelLayout.setVerticalGroup(
            winnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winnerPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(notTop10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(finishGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGameButtonActionPerformed
        dispose();
        //this.setVisible(true);
    }//GEN-LAST:event_finishGameButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishGameButton;
    private javax.swing.JLabel notTop10Label;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JPanel winnerPanel;
    // End of variables declaration//GEN-END:variables
}
