/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mortalkombat.Forms;

import com.mycompany.mortalkombat.WTF.Result;
import com.mycompany.mortalkombat.WTF.ResultManager;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MyHuawei
 */
public class RecordTabDialog extends javax.swing.JDialog {

    /**
     * Creates new form RecordTabDialog
     */
    public RecordTabDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updateResultsTable();
    }
    private void updateResultsTable() {
        List<Result> results = ResultManager.getResults(); // если статический менеджер
        String[] columnNames = {"Имя", "Очки"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        int top = Math.min(results.size(), 10);
        for (int i = 0; i < top; i++) {
            Result r = results.get(i);
            Object[] row = {r.getName(), r.getPoints()};
            model.addRow(row);
        }
        recordTable.setModel(model); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordTabPanel = new javax.swing.JPanel();
        recordTabLabel = new javax.swing.JLabel();
        recordTabScrollPane = new javax.swing.JScrollPane();
        recordTable = new javax.swing.JTable();
        closeTabButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        recordTabPanel.setBackground(new java.awt.Color(204, 204, 255));

        recordTabLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        recordTabLabel.setForeground(new java.awt.Color(51, 51, 51));
        recordTabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recordTabLabel.setText("Таблица рекордов");

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordTable.setAutoscrolls(false);
        recordTabScrollPane.setViewportView(recordTable);

        closeTabButton.setBackground(new java.awt.Color(255, 255, 153));
        closeTabButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeTabButton.setForeground(new java.awt.Color(51, 51, 51));
        closeTabButton.setText("Закрыть");
        closeTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTabButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordTabPanelLayout = new javax.swing.GroupLayout(recordTabPanel);
        recordTabPanel.setLayout(recordTabPanelLayout);
        recordTabPanelLayout.setHorizontalGroup(
            recordTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordTabPanelLayout.createSequentialGroup()
                .addGroup(recordTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(closeTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(recordTabPanelLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(recordTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)))
                    .addGroup(recordTabPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(recordTabScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recordTabPanelLayout.setVerticalGroup(
            recordTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordTabPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(recordTabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordTabScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeTabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeTabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTabButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeTabButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeTabButton;
    private javax.swing.JLabel recordTabLabel;
    private javax.swing.JPanel recordTabPanel;
    private javax.swing.JScrollPane recordTabScrollPane;
    private javax.swing.JTable recordTable;
    // End of variables declaration//GEN-END:variables
}
