/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mortalkombat.Forms;


/**
 *
 * @author MyHuawei
 */
public class RoundResultDialog extends javax.swing.JDialog {

    /**
     * Creates new form RoundResultDialog
     */
    public RoundResultDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundResultPanel = new javax.swing.JPanel();
        roundResultLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundResultPanel.setBackground(new java.awt.Color(179, 226, 217));

        roundResultLabel.setBackground(new java.awt.Color(204, 204, 204));
        roundResultLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        roundResultLabel.setForeground(new java.awt.Color(204, 0, 0));
        roundResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundResultLabel.setText("roundResultLabel");
        roundResultLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nextButton.setBackground(new java.awt.Color(114, 218, 142));
        nextButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nextButton.setText("Дальше");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundResultPanelLayout = new javax.swing.GroupLayout(roundResultPanel);
        roundResultPanel.setLayout(roundResultPanelLayout);
        roundResultPanelLayout.setHorizontalGroup(
            roundResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundResultPanelLayout.createSequentialGroup()
                .addGroup(roundResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundResultPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundResultPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(roundResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        roundResultPanelLayout.setVerticalGroup(
            roundResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundResultPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(roundResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    public void setResultLabel(String result){
        roundResultLabel.setText(result);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel roundResultLabel;
    private javax.swing.JPanel roundResultPanel;
    // End of variables declaration//GEN-END:variables
}
