/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mortalkombat.Forms;


import com.mycompany.mortalkombat.WTF.Fight;
import com.mycompany.mortalkombat.WTF.Players.Human;

/**
 *
 * @author MyHuawei
 */
public class WinDialog extends javax.swing.JDialog {

    private final Fight fight;
    private final Human human;
    /**
     * Creates new form WinDialog
     */
    public WinDialog(java.awt.Frame parent, boolean modal, Fight fight, Human human) {
        super(parent, modal);
        this.fight = fight;
        this.human = human;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winnerTop10Panel = new javax.swing.JPanel();
        winnerTop10Label = new javax.swing.JLabel();
        winnerNameTextField = new javax.swing.JTextField();
        winnerTop10InfoLabel1 = new javax.swing.JLabel();
        winnerTop10InfoLabel2 = new javax.swing.JLabel();
        finishGameTop10Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winnerTop10Panel.setBackground(new java.awt.Color(255, 204, 255));

        winnerTop10Label.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winnerTop10Label.setForeground(new java.awt.Color(255, 0, 0));
        winnerTop10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerTop10Label.setText("Победа на вашей стороне");

        winnerNameTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        winnerNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        winnerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winnerNameTextFieldActionPerformed(evt);
            }
        });

        winnerTop10InfoLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winnerTop10InfoLabel1.setForeground(new java.awt.Color(102, 102, 102));
        winnerTop10InfoLabel1.setText("Введите имя своего персонажа для добавления");

        winnerTop10InfoLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winnerTop10InfoLabel2.setForeground(new java.awt.Color(102, 102, 102));
        winnerTop10InfoLabel2.setText("результата в таблицу рекордов");

        finishGameTop10Button.setBackground(new java.awt.Color(153, 153, 255));
        finishGameTop10Button.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishGameTop10Button.setForeground(new java.awt.Color(51, 51, 51));
        finishGameTop10Button.setText("Закончить игру");
        finishGameTop10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGameTop10ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winnerTop10PanelLayout = new javax.swing.GroupLayout(winnerTop10Panel);
        winnerTop10Panel.setLayout(winnerTop10PanelLayout);
        winnerTop10PanelLayout.setHorizontalGroup(
            winnerTop10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winnerTop10PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(finishGameTop10Button)
                .addGap(14, 14, 14))
            .addGroup(winnerTop10PanelLayout.createSequentialGroup()
                .addGroup(winnerTop10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winnerTop10PanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(winnerTop10InfoLabel2))
                    .addGroup(winnerTop10PanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(winnerTop10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winnerTop10PanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(winnerTop10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winnerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(winnerTop10InfoLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        winnerTop10PanelLayout.setVerticalGroup(
            winnerTop10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winnerTop10PanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(winnerTop10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(winnerTop10InfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winnerTop10InfoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(winnerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishGameTop10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winnerTop10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winnerTop10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void winnerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winnerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_winnerNameTextFieldActionPerformed

    private void finishGameTop10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGameTop10ButtonActionPerformed
        fight.finishGameAndUpdateTop(human, winnerNameTextField.getText());
        dispose();
        winnerNameTextField.setText("");
    }//GEN-LAST:event_finishGameTop10ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishGameTop10Button;
    private javax.swing.JTextField winnerNameTextField;
    private javax.swing.JLabel winnerTop10InfoLabel1;
    private javax.swing.JLabel winnerTop10InfoLabel2;
    private javax.swing.JLabel winnerTop10Label;
    private javax.swing.JPanel winnerTop10Panel;
    // End of variables declaration//GEN-END:variables
}
